### ISSUE TITLE
attribute incompatability sihywtcamc-1.3+1.16.5

### ISSUE THREAD

**Issue by SpinnyBoiii** [sf-inc/sihywtcamc#21]
noticed this cause i was testing with some of the origins mods, but having the reach attribute enabled in the tools config will result in it overriding any changes done to a player's reach by other mods.
i m currently unable to test it with the other attributes, but if the mod functions the same way there then it will likely have the same result.

**Comment by charlyb01** [comment]
Hi, thanks for the report! I will add it to the compatibility issues. The problem seems pretty fair: I'm changing the way reach is computed so it creates issues with mods doing the same thing. I'm not sure I can do anything about it as the reach attribute was a struggle to work on. HOWEVER, I will still check if I can improve the way I implemented it, and how Origins did that to know if there is a chance both work together =)
I will tell you again later in the week!

**Comment by Nathan22211** [comment]
it's because you're not using james white shirt's reach attribute API 'https://maven.jamieswhiteshirt.com/libs-release/' point your Gradle to that repo and include the reach API and that should fix things with some reconfiguring

**Comment by charlyb01** [comment]
Hi @Nathan22211 ! Thanks for the suggestion, I had already discovered this when I looked for a solution and that's why I removed the wontfix label. I'm going to update it soon but I had a setback. This should come in the coming days, thanks again
