### ISSUE TITLE
Feature request: Config Reorganisation

### ISSUE THREAD

**Issue by AzureMonument** [sf-inc/sihywtcamc#24]
So I'm playing a heavy-modded custom modpack. It adds... quite a bit of tools and weapons. The fact I can add them in the config is great- but _man_ is it a slog. Just the stone (level) _swords_ alone take up 48 lines- and that's with me reducing the size from 6 lines per weapon down to four by moving the brackets. And I still have to do every single tool and such.
![image](https://user-images.githubusercontent.com/43318292/129366511-9eeaa4db-656c-42f6-871b-467b869c60db.png)

It'd be nice if the config was made in such a way that it uses an array to get the names of items and then applies the following attributes as normal. I.e:
{ identifiers: [minecraft:stone_sword, sentimentality3:granite_sword, ...extera...],
  attackDamage: 4.0,
  attackSpeed: 3.0,
  attackReach: 3.0 }

Thus allowing a stupid amount of space and alot of copy+pasting to be saved.
Don't know if this is actually possible, but it would be greatly appreciated. Thank you for your time and the mod~

**Comment by charlyb01** [comment]
This was actually a struggle to allow other mods weapons in the configs, but yeah I understand yours too ^^
I will see what I can do, but your idea seems great. Thanks a lot =)

**Comment by charlyb01** [comment]
Okay, I changed it the way you wanted so that it takes less lines ;)
I attach you a beta version because I'm a bit lazy to test with mods and I guess you already have a file doing this, or you just have to change a few lines. IMPORTANT: Note that you'll need to delete (or move somewhere else) your old config file so that it will generate a proper one.
[sihywtcamc-beta.zip](https://github.com/sf-inc/sihywtcamc/files/6983972/sihywtcamc-beta.zip)

**Comment by charlyb01** [comment]
I tested it and it works ;)

**Comment by AzureMonument** [comment]
Thanks! I just got on this morning, so I'll also load it up in a bit.
