### ISSUE TITLE
[Feature suggestion] Hold attack button to keep attacking

### ISSUE THREAD

**Issue by Ninjabros156** [sf-inc/sihywtcamc#28]
I felt this mod is good but I feel somethings are missing so can u add the ability to hold the attack button as an option please?

**Comment by charlyb01** [comment]
I guess that would make sense in this mod, as it's also a feature that came with the Combat update if I'm right.
Don't have much time for now, but this will definitely come in the future ;)

**Comment by 4zy1** [comment]
would love this

**Comment by charlyb01** [comment]
When starting to work again on this mod, in order to add many other features from combat snapshots, someone mentioned that [Combatify](https://modrinth.com/mod/combatify) is a mod that does exactly this: adding every feature from combat snapshots. As I don't do duplicate mods, I decided to stop adding features from combat snapshots, and I will even remove the ones I already added to the next release that will be for the next Minecraft major version.

By doing so, this mod will focus on adding only original features to combat. This will be way easier for me to maintain and avoid duplicate functionalities, when one mod is already doing the work correctly.
