### ISSUE TITLE
conflict-1.20.1fabric

### ISSUE THREAD

**Issue by zc1108aaa** [sf-inc/sihywtcamc#36]
[crash-2024-09-03_12.16.34-client.txt](https://github.com/user-attachments/files/16843398/crash-2024-09-03_12.16.34-client.txt)
0
[latest.log](https://github.com/user-attachments/files/16843399/latest.log)

**Comment by charlyb01** [comment]
Hi, thanks for the report! Sadly, I don't have enough time to maintain this mod. I just updated to 1.21 though, and in this version there won't be the incompatibility as enchantments were updated in minecraft (and also because I removed a few features during the port). So, this won't be fixed in 1.20.1
